# Generated by Django 4.2.7 on 2023-11-06 18:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldt_app', '0002_customuser_task_end_dt_task_start_dt_taskhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Junior', 'Младший'), ('Middle', 'Средний'), ('Senjor', 'Старший')], max_length=30, verbose_name='Уровень')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='email адрес')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('network', models.JSONField(blank=True, verbose_name='Соцсети')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_dt',
            new_name='date_finished',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='task_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_dt',
        ),
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(default='admin', max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Токен'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 19, 5, 504172), verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Описание задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Задача', max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Назначенный сотрудник'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('FREE', 'Свободна'), ('TAKEN', 'В работе'), ('ALARM', 'Форс-мажор'), ('FINISHED', 'Завершена')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='new_status',
            field=models.CharField(choices=[('FREE', 'Свободна'), ('TAKEN', 'В работе'), ('ALARM', 'Форс-мажор'), ('FINISHED', 'Завершена')], help_text='Новый статус задачи', max_length=32, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('FREE', 'Свободна'), ('TAKEN', 'В работе'), ('ALARM', 'Форс-мажор'), ('FINISHED', 'Завершена')], help_text='Предыдущий статус задачи', max_length=32, null=True, verbose_name='Старый статус'),
        ),
        migrations.CreateModel(
            name='Gis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('long', models.FloatField(verbose_name='Долгота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldt_app.profile', verbose_name='Данные пользователя'),
        ),
    ]
