# Generated by Django 4.2.7 on 2023-11-09 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldt_app', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 22, 18, 28, 739394), verbose_name='Дата и время создания'),
        ),
    ]
