# Generated by Django 4.2.7 on 2023-11-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAVEL', 'Выезд на точку'), ('TEACH', 'Обучение агента'), ('CARD', 'Доставка карт')], max_length=30, verbose_name='Тип задачи')),
                ('status', models.CharField(choices=[('FREE', 'Свободна'), ('TAKEN', 'В работе'), ('FINISHED', 'Завершена')], max_length=30, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], verbose_name='Приоритет')),
            ],
        ),
    ]
