# Generated by Django 4.2.7 on 2023-11-04 15:27

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ldt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('grade', models.CharField(choices=[('Junior', 'Младший'), ('Middle', 'Средний'), ('Senjor', 'Старший')], max_length=30, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата и время выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_dt',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 15, 27, 37, 101976), verbose_name='Дата и время создания'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('FREE', 'Свободна'), ('TAKEN', 'В работе'), ('FINISHED', 'Завершена')], help_text='Предыдущий статус задачи', max_length=32, null=True, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('FREE', 'Свободна'), ('TAKEN', 'В работе'), ('FINISHED', 'Завершена')], help_text='Новый статус задачи', max_length=32, verbose_name='Новый статус')),
                ('change_datetime', models.DateTimeField(auto_now_add=True, help_text='Дата и время изменения статуса', verbose_name='Дата и время изменения статуса')),
                ('task', models.ForeignKey(help_text='Задача', on_delete=django.db.models.deletion.CASCADE, to='ldt_app.task')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь производивший изменение статуса задачи', null=True, on_delete=django.db.models.deletion.PROTECT, to='ldt_app.customuser')),
            ],
            options={
                'verbose_name': 'История изменений задачи',
                'verbose_name_plural': 'История изменений задачи',
            },
        ),
    ]
